story_1 = ['Once upon a time there was a magical kingdom nestled next to a dazzling Crystal Forest.',
           'This special forest glimmered with gemstones and crystals of all shapes and sizes.',
           'Crystal flowers sprouted from the earth, diamonds dangled from branches, and rubies glittered like ripe berries.',
           'The Crystal Forest was guarded by Sir Glint, a noble knight whose silver armor shone as brightly as the crystals themselves. As Sir Glint patrolled through the shimmering woods each day on his white horse, sunlight streaming through the trees caused his armor to flash with brilliant rainbows of light.',
           'The villagers who lived near the forest loved gazing at the glinting trees. At sunset when the sky turned pink, the crystals took on a magical rosy glow. The forest was the pride and joy of the entire kingdom.',
           'One sunny morning, Sir Glint embarked on his regular patrol. But as he rode down the forest paths, he noticed something strange - some of the crystals appeared dull instead of dazzling! Their normal luster was faded and lackluster.',
           'Puzzled, Sir Glint followed the trail of the dim crystals. He came upon a rocky clearing where to his alarm, he saw a crew of miners hacking away at the crystal trees with pickaxes! They were shoveling armloads of shimmering gems into their bulging sacks.',
           '"Halt at once!" yelled Sir Glint. "You are harming the Crystal Forest!" But the greedy miners ignored him, focused only on gathering more glittering treasure.',
           '''Sir Glint realized if he didn't intervene, the miners would plunder the forest until no crystals remained. He boldly drew his sword and commanded, "Stop this destruction! You must cease mining the crystals before it is too late.''',
           ]

story_2 = [
    'Once upon a time in the enchanted realm of Light Valley, there lived a valiant knight named Lumen. He was sworn protector of the valley, famed for its magical golden light that nourished the land. Lumen patrolled proudly atop his noble steed each dawn as sunshine flooded the orchards and meadows.',
    'But one misty morn, an ominous darkness swallowed up the valley! "What evil lurks here?" Lumen wondered. Suddenly, a colossal inky beast with glowing crimson eyes and smoky tendrils materialized from the blackness.',
    '"I am the Shadow Beast!" it thundered. "For too long, mortals in this valley have squandered their precious light at night, denying rest to the land. Now their wasteful ways have called me forth to block the dawn and cast all into eternal midnight!"',
    'The Shadow Beast unfurled its swirling form, expanding to blot out the sun completely. Shrieks rang out across the vale below as crops and flowers withered without light.',
    'Lumen drew his crystalline sword, which blazed with stored sunshine. "Your darkness will not prevail!" he declared. Lumen charged the Shadow Beast, striking blow after blow. But the shadows engulfed his shining sword, dampening its luminance until Lumen had to retreat.',
    "As the knight regrouped, he realized the Shadow Beast was right - the people had been careless with light, denying the valley's natural cycles. But he knew hope remained. With wisdom and care, day's radiance could still be restored!",
    'So Lumen journeyed to the cluster of villages now cast in gloom. "People of the valley, we must work together to replenish our lands light and dispel this darkness!" he urged. "We must use illumination wisely - only at appropriate times, and only in moderation."',
    'At first, the fearful villagers refused to listen. "Light one torch, and the Beast will swallow us whole!" they cried. But Lumen gently persisted, reminding them of the valley bounty when natural rhythms were honored.',
    'Finally, the villagers agreed to conserve illumination and respect night\'s presence. "Teach us to use light in harmony," they begged Lumen. So he showed them how to harvest sunshine during the day to store in crystals, then carefully ration emanations each evening."',
    "Soon a hopeful glow returned to the valley as careful stewardship of light was restored. With Lumen's guidance, the villages installed twilight timers on their lanterns. The people gained skills to harness even starlight\'s subtle gleam for essential tasks after dusk.",
    "One twilit eve, Lumen gazed up to see the Shadow Beast fading as balance returned. 'Your existence shall burden this land no more,' the knight declared. With joyful cheers, the people celebrated Light Valley's liberation back into dawn's warmth.",
    "From then on, the inhabitants honored the cycles of light and darkness. Thanks to their cooperation and Lumen's wisdom, the valley remained luminous, fertile, and flourishing for ages to come. The end."]

story_3 = ['Once upon a time there was a magical kingdom nestled next to a dazzling Crystal Forest.',
           'This special forest glimmered with gemstones and crystals of all shapes and sizes.',
           'Puzzled, Sir Glint followed the trail of the dim crystals. He came upon a rocky clearing where to his alarm, he saw a crew of miners hacking away at the crystal trees with pickaxes! They were shoveling armloads of shimmering gems into their bulging sacks.',
           '"Halt at once!" yelled Sir Glint. "You are harming the Crystal Forest!" But the greedy miners ignored him, focused only on gathering more glittering treasure.',
           '''Sir Glint realized if he didn't intervene, the miners would plunder the forest until no crystals remained. He boldly drew his sword and commanded, "Stop this destruction! You must cease mining the crystals before it is too late.''',
           ]

story_3_cut_a = [
           '"Halt at once!"',
            'yelled Sir Glint.',
            '"You are harming the Crystal Forest!"',
            'But the greedy miners ignored him, focused only on gathering more glittering treasure.',
           '''Sir Glint realized if he didn't intervene, the miners would plunder the forest until no crystals remained. He boldly drew his sword and commanded, "Stop this destruction! You must cease mining the crystals before it is too late.''',
           ]

story_3_cut_b = [
    '"Halt at once!", yelled Sir Glint. "You are harming the Crystal Forest!". But the greedy miners ignored him, focused only on gathering more glittering treasure.',
    '''Sir Glint realized if he didn't intervene, the miners would plunder the forest until no crystals remained. He boldly drew his sword and commanded, "Stop this destruction! You must cease mining the crystals before it is too late.'''
    ]

story_4 = [
    'Not long into his journey, Dino met a cheerful bird named Bella. Bella had feathers as blue as the sky and a voice as sweet as honey. "Hello there! Where are you off to on this fine day?" chirped Bella, fluttering around Dino.',
    '"I\'m off on an adventure to see what lies beyond our forest," Dino replied with a grin.',
    '"That sounds wonderful! May I join you?" asked Bella, her eyes sparkling with curiosity.',
    '"Of course! The more, the merrier!" exclaimed Dino, and together they continued deeper into the forest.',
    'As they ventured further, they encountered a babbling brook, its waters crystal clear and cool. They stopped to drink, and it was there they met Finley, a friendly fish who swam up to greet them. "Hello, travelers! What brings you to my brook?" Finley asked, his scales glinting in the sunlight.',
    '"We\'re on an adventure to explore the world beyond our home," Dino explained, his voice filled with excitement.',
    '"How exciting! I\'ve always wanted to see what lies beyond this brook. May I join you on your journey?" Finley bubbled eagerly.',
    '"With pleasure, Finley! You can guide us through the waters," Dino said, laughing.']

story_5 = ['Once upon a time there was a magical kingdom nestled next to a dazzling Crystal Forest.',
           'Puzzled, Sir Glint followed the trail of the dim crystals. He came upon a rocky clearing where to his alarm, he saw a crew of miners hacking away at the crystal trees with pickaxes! They were shoveling armloads of shimmering gems into their bulging sacks.',
           '"Halt at once!" yelled Sir Glint. "You are harming the Crystal Forest!" But the greedy miners ignored him, focused only on gathering more glittering treasure.',
           '''Sir Glint realized if he didn't intervene, the miners would plunder the forest until no crystals remained. He boldly drew his sword and commanded, "Stop this destruction! You must cease mining the crystals before it is too late.''',
           ]


story_db_3 = [
    'Once upon a time in the enchanted realm of Light Valley, there lived a valiant knight named Lumen.',
    'He was sworn protector of the valley, famed for its magical golden light that nourished the land. ',
    'Lumen patrolled proudly atop his noble steed each dawn as sunshine flooded the orchards and meadows.',
    'But one misty morn, an ominous darkness swallowed up the valley! "What evil lurks here?" Lumen wondered. ',
    'Suddenly, a colossal inky beast with glowing crimson eyes and smoky tendrils materialized from the blackness.',
    '"I am the Shadow Beast!" it thundered. "For too long, mortals in this valley have squandered their precious light at night, denying rest to the land. ',
    'Now their wasteful ways have called me forth to block the dawn and cast all into eternal midnight!"',
    'The Shadow Beast unfurled its swirling form, expanding to blot out the sun completely. ',
    'Shrieks rang out across the vale below as crops and flowers withered without light.',
    'Lumen drew his crystalline sword, which blazed with stored sunshine. "Your darkness will not prevail!" he declared. ',
    'Lumen charged the Shadow Beast, striking blow after blow. But the shadows engulfed his shining sword, dampening its luminance until Lumen had to retreat.',
    'As the knight regrouped, he realized the Shadow Beast was right - the people had been careless with light, denying the valley\'s natural cycles. ',
    'But he knew hope remained. With wisdom and care, day\'s radiance could still be restored!',
    'So Lumen journeyed to the cluster of villages now cast in gloom. "People of the valley, we must work together to replenish our land\'s light and dispel this darkness!" he urged. ',
    '"We must use illumination wisely - only at appropriate times, and only in moderation."',
    'At first, the fearful villagers refused to listen. "Light one torch, and the Beast will swallow us whole!" they cried. ',
    'But Lumen gently persisted, reminding them of the valley\'s bounty when natural rhythms were honored.',
    'Finally, the villagers agreed to conserve illumination and respect night\'s presence. "Teach us to use light in harmony," they begged Lumen. ',
    'So he showed them how to harvest sunshine during the day to store in crystals, then carefully ration emanations each evening.',
    'Soon a hopeful glow returned to the valley as careful stewardship of light was restored. ',
    'With Lumen\'s guidance, the villages installed twilight timers on their lanterns. ',
    'The people gained skills to harness even starlight\'s subtle gleam for essential tasks after dusk.',
    'One twilit eve, Lumen gazed up to see the Shadow Beast fading as balance returned. ',
    '"Your existence shall burden this land no more," the knight declared. With joyful cheers, the people celebrated Light Valley\'s liberation back into dawn\'s warmth.',
    'From then on, the inhabitants honored the cycles of light and darkness. ',
    'Thanks to their cooperation and Lumen\'s wisdom, the valley remained luminous, fertile, and flourishing for ages to come. The end.'
]

story_db_3_cut = [
    'Once upon a time in the enchanted realm of Light Valley, there lived a valiant knight named Lumen.',
    'He was sworn protector of the valley, famed for its magical golden light that nourished the land. ',
    'Lumen patrolled proudly atop his noble steed each dawn as sunshine flooded the orchards and meadows.',
    'But one misty morn, an ominous darkness swallowed up the valley!',
    '"What evil lurks here?"',
    'Lumen wondered. ',
    'Suddenly, a colossal inky beast with glowing crimson eyes and smoky tendrils materialized from the blackness.',
    '"I am the Shadow Beast!"'
    ' it thundered. "For too long, mortals in this valley have squandered their precious light at night, denying rest to the land. ',
    'Now their wasteful ways have called me forth to block the dawn and cast all into eternal midnight!"',
    'The Shadow Beast unfurled its swirling form, expanding to blot out the sun completely. ',
    'Shrieks rang out across the vale below as crops and flowers withered without light.',
    'Lumen drew his crystalline sword, which blazed with stored sunshine. "Your darkness will not prevail!" he declared. ',
    'Lumen charged the Shadow Beast, striking blow after blow. But the shadows engulfed his shining sword, dampening its luminance until Lumen had to retreat.',
    'As the knight regrouped, he realized the Shadow Beast was right - the people had been careless with light, denying the valley\'s natural cycles. ',
    'But he knew hope remained. With wisdom and care, day\'s radiance could still be restored!',
    'So Lumen journeyed to the cluster of villages now cast in gloom. "People of the valley, we must work together to replenish our land\'s light and dispel this darkness!" he urged. ',
    '"We must use illumination wisely - only at appropriate times, and only in moderation."',
    'At first, the fearful villagers refused to listen. "Light one torch, and the Beast will swallow us whole!" they cried. ',
    'But Lumen gently persisted, reminding them of the valley\'s bounty when natural rhythms were honored.',
    'Finally, the villagers agreed to conserve illumination and respect night\'s presence. "Teach us to use light in harmony," they begged Lumen. ',
    'So he showed them how to harvest sunshine during the day to store in crystals, then carefully ration emanations each evening.',
    'Soon a hopeful glow returned to the valley as careful stewardship of light was restored. ',
    'With Lumen\'s guidance, the villages installed twilight timers on their lanterns. ',
    'The people gained skills to harness even starlight\'s subtle gleam for essential tasks after dusk.',
    'One twilit eve, Lumen gazed up to see the Shadow Beast fading as balance returned. ',
    '"Your existence shall burden this land no more," the knight declared. With joyful cheers, the people celebrated Light Valley\'s liberation back into dawn\'s warmth.',
    'From then on, the inhabitants honored the cycles of light and darkness. ',
    'Thanks to their cooperation and Lumen\'s wisdom, the valley remained luminous, fertile, and flourishing for ages to come. The end.'
]

story_db_4 = [
    'Once upon a time in the breezy kingdom of Windmill Village, there lived a gallant knight named Ser Gust. '
    'He was a brave and honest soul, dedicated to protecting the land and people. Ser Gust would often patrol the soaring hills surrounding the village atop his noble steed. ',
    'Seeing the towering windmills spin steadily in the windswept hills filled Ser Gust with pride.',
    'The windmills used the endless gusts to grind grain into flour for bread.',
    'They pumped cool well water to the village fountains. ',
    'At night, their swirling motion even charged lamps that lit the village streets. ',
    'The windmills powered and sustained the whole community with the help of blustery winds.',
    'But one frigid morning, as Ser Gust embarked on his patrol, an eerie silence filled the usually whistling hills. ',
    'As his horse climbed higher, Ser Gust was shocked to see the giant windmill sails hanging lifeless and still.',
    'No breezes seemed to stir at all!',
    'Riding into the village, he found the people in a state of despair. ',
    'The bakers had no flour for bread, the fountains trickled weakly, and after sunset, darkness swallowed the unlit streets.',
    '"It\'s the wind!" cried one villager. "Somehow it has vanished, leaving our windmills useless hunks!"',
    'Ser Gust calmed the people, vowing to solve this mystery at once. ',
    'He consulted with elders and inventors, climatologists and engineers, seeking answers. ',
    'Many nights, Ser Gust stayed awake pondering what could have robbed the land of its reliable winds.',
    'Finally, old Marus the weather sage revealed the truth. "We have become greedy," he confessed. "Our windmill farming was so aggressive, using up every gust and zephyr, that we exhausted nature\'s bounty." ',
    'Ser Gust knew Marus spoke wisely. The people\'s excessive needs had damaged the very source of their livelihood.',
    'At dawn, Ser Gust announced a village meeting, saying "People, we must make amends with nature. ',
    'I propose we build smaller, more efficient windmills and space them to share winds without depleting them." Murmurs rippled through the crowd. ',
    'Could they achieve balance once more?',
    'The work began swiftly as the village united around Ser Gust`\'s plan. ',
    'They dismantled the gigantic windmills and reshaped their parts into multiple slim, short-spired mills. ',
    'These dotted the hills spaced wide apart so breezes could swirl between them unimpeded. The people eagerly awaited the results.',
    'After many anxious days, a gentle breeze arose one morning. ',
    'It playfully spun the new windmill sails faster and faster! The bakers\' ovens roared with flame, fountains gushed refreshed, and streets glowed cheerily under twinkling lamps once again. The village was restored.',
    'Cheers rang out for the brave Ser Gust. ',
    'In his wisdom, the land\'s harmony was renewed and their future secured. ',
    'From that day forth, the people practiced gratitude and care when harnessing nature\'s gifts. And Ser Gust remained a vigilant protector should balance ever falter. ',
    'The village continued thriving in the embrace of the wild and gentle winds they had learned to respect.'
]

story_db_34 = [
    'Once upon a time there was a valorous knight named Ironwing who rode among the Floating Cloud Islands of Sky Arbor on his loyal pegasus Charger. ',
    'Ironwing had armor of glimmering silver and massive wings that allowed him to soar between the islands on missions of protection.',
    'Ironwing and his fellow knights of the Cloud Calvary ensured all creatures in Sky Arbor lived free from harm.',
    'Their island home floated high in an endless blue sky, circling slowly through the seasons. ',
    'It was a haven for rare winged wildlife.',
    'Flocks of twittering bluebirds, pride of lively griffins, and rainbows of dancing dragonflies all made Sky Arbor their home.',
    'Ironwing had sworn an oath to defend their peace and freedom.',
    'Each morning, Ironwing scouted between the scattered islands to visit with the avian residents and address any concerns. ',
    'One bright spring day, he came upon a tribe of unhappy phoenixes.',
    '"Please Ironwing, you must stop the Cloud Shepherds from letting their flocks overgraze our nesting cliffs," the phoenix elder said. ',
    'Ironwing could see the shepherds\' wayward sheep had stripped the vegetation bare.',
    '"Fear not, I will speak with them," promised Ironwing. Charger sailed them swiftly to the shepherds\' island. ',
    'Ironwing helped the men rearrange their fences to steer the sheep away from phoenix nest sites.',
    'On another island, Ironwing found some storm pixies carelessly leaving gates open at the unicorn stables.',
    'Two rare spirited unicorns had already wandered free into dangerous open sky!',
    'With the help of his fellow knights, Ironwing safely wrangled the straying unicorns home. ',
    '"We must keep their home secure so these marvels endure," Ironwing gently told the apologetic pixies \as they locked the gates.',
    'At a council of the Sky Islands\' inhabitants, Ironwing suggested they each pledge to be stewards helping conserve their home for all. ',
    'Every creature agreed, wanting to preserve nature\'s gifts.',
    'Soon Ironwing\'s Knights of the Cloud Calvary were busy building nest boxes for the bluebirds, planting wild meadows for dragonflies, and tracking the health of all species. ',
    'Creatures lived in harmony, protecting each other.',
    'Word of Ironwing\'s wise conservation spread on the winds, reaching isles everywhere. ',
    'nspired, more brave knights rose up to defend the winged wildlife of their homelands with care and compassion.',
    'On his travels, Ironwing smiled to see once-endangered phoenix flocks now thriving again across multiple skies. ',
    'This renewal lifted his spirit like the triumphant song of the phoenix reborn.',
    'And so the Floating Cloud Islands of Sky Arbor remained a heavenly sanctuary watched over by good Sir Ironwing and his knights. ',
    'Their dutiful example taught that with respect and understanding, all creatures may dwell safely together under nature\'s gentle grace.',
    'The end.',

]

story_db_36 = [
    'Once upon a time in the magical kingdom of Morphland, there lived a brave chameleon knight named Marshal Metamorphic. ',
    'He was renowned throughout the land for his camouflaging abilities that allowed him to blend seamlessly into any surroundings.',
    'Marshal Metamorphic patrolled Morphland atop his trusty steed Chamomile, a perfectly camouflaged chameleon horse. ',
    'Together they safeguarded the wondrous biodiversity of the ever-changing landscapes.',
    'Morphland\'s many ecosystems each had unique plants and creatures perfectly adapted to their terrain. ',
    'There were sunny meadows dotted with rainbow wildflowers, ancient moss-draped forests, misty highland crags, and bubbling wetlands.',
    'Wherever they traveled, Marshal Metamorphic and Chamomile would shift their scales to match the local colours. ',
    'Blending into the environment made them excellent protectors. They defended vulnerable habitats from any who would damage them.',
    'One day, a visiting king was so impressed by Marshal Metamorphic, he offered him rule over half the kingdom if the knight would swear allegiance. ',
    'But Marshal declined, saying his duty was to the land itself, not any one leader. ',
    'His loyal friends - the animals, trees, and stones - were subjects enough for him.',
    'Marshal Metamorphic gathered allies from diverse ecosystems - falcons from the cliffs, moles from the meadows, trout from the rivers. ',
    'At his home base of Camo Castle, he trained them as "morph rangers" to monitor environmental health.',
    'When needs arose, the morph rangers adapted to assist. ',
    'Falcons used sharp eyes to spot invaders. ',
    'Moles dug channels to redirect water. Trout engineered underwater shelters for fauna. ',
    'Together they kept harmony through nature\'s changes.',
    'One summer, dry winds swept over Morphland. The morph rangers sprang into action, transporting water buckets to thirsty trees, relocating reptile eggs to shadier nests. ',
    'Their care averted a crisis. The knight and allies celebrated the cooperation of all creatures great and small.',
    'Marshal Metamorphic\'s humble dedication spread by example. ',
    'Soon knights throughout the kingdom were laying down arms to nurture fragile lake ecosystems. ',
    'Dragon clans chose to coexist with mountain inhabitants rather than claim peaks solely for themselves.',
    'Within a few generations, Morphland transformed into a flourishing paradise. ',
    'Diverse beings lived interdependently, realizing that what sustained one, sustained all. '
    'They had Marshal Metamorphic to thank for this enlightened age. ',
    'His selfless actions rippled into waves of compassion that became the new way of the land.',
    'And they all lived sustainability ever after! The end.'
]

story_db_37 = [
    'Once upon a time in a faraway realm, there lived a noble knight named Sir Aqua who had a remarkable secret - he could transform into a water lily! ',
    'You see, in this mystical kingdom every person and creature had the power to shapeshift into a plant.',
    'For knights and warriors like Sir Aqua, this gave them the unique ability to blend into nature itself. ',
    'By morphing into leaves, flowers, or trees, they could evade capture and slip away unseen into the forests.',
    'Sir Aqua looked like any other chivalrous knight adorned in silver armor and a flowing blue cape. ',
    'But when touching water, he would instantly take the form of a graceful white water lily blossoming across the surface.',
    'Though he could become a soldier-lily hybrid in battle, Sir Aqua preferred lingering peacefully as a bloom atop the pond, giving resting insects a place to dock. ',
    'He felt tranquil and connected to the natural realm in plant form.',
    'However, many other knights rarely used their plant powers except when necessary for subterfuge. ',
    'They saw their true shapes as more important, looking down on passive plants. ',
    'These knights rampaged across the lands carelessly trampling gardens and setting forests ablaze without regard for the flora.',
    'Sir Aqua was disheartened by their destructiveness and disregard for plant life. ',
    'He recruited trusted allies - a squirrel named Scamp who transformed into an oak tree, a rabbit called Thumper who became a snapdragon, and Delia the deer whose flower form was a daffodil.',
    'Together, Sir Aqua\'s shape-shifting squad performed rescue missions across the realms. ',
    'They planted seeds to regrow burned woods, created rivers to nourish dried lands, and brought wilted gardens back to life. They worked in harmony with their environments, using their powers to nurture the lands.',
    'Soon others were inspired by their efforts and joined in. ',
    'Beings realized plant forms could be embraced, not shunned. ',
    'Knights started sprouting flowers from their armor, while children rejoiced shape-shifting into their favorite plant species. ',
    'Forests and meadows flourished as all worked together to foster nature.',
    'In time, the kingdom became a bountiful paradise where flowers bloomed eternally and crops bore harvests three seasons a year. ',
    'Symbiotic living let all life forms thrive.',
    'Sir Aqua\'s grand vision revealed that valuing the contributions of even the smallest sapling helps foster a prosperous world for all creatures. The end.'
]

